name: Linter

on:
  push:
    branches:
      - dev
      - master
jobs:
  linter:
    name: 'Linter ${{matrix.name}}'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - path: 'api'
            name: 'back'
          - path: 'front'
            name: 'front'

    steps:
      # Setup job
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Node modules cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys:
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install packages
        working-directory: ${{matrix.path}}
        run: npm ci

      - name: Lint Code
        working-directory: ${{matrix.path}}
        run: npm run lint

      - name: Build Code
        working-directory: ${{matrix.path}}
        run: npm run build --if-present